version: "3"

services:
    todo-web-app:
        build: .
        container_name: todo-web-app
        ports:
          - "3000:3000"
        volumes:
          - .:/usr/src/app
          - ./node_modules:/usr/src/app/node_modules
